name: poke_reader
description: A Flutter app project for reading info about Pokémon from the PokeApi

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^0.1.3
    flutter_bloc: ^6.0.5
    equatable: ^1.2.5
    json_annotation: ^3.0.1
    tuple: ^1.0.3
    dio: ^3.0.10

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^1.10.1
    json_serializable: ^3.4.1
    flutter_launcher_icons: ^0.8.0

flutter:
    uses-material-design: true

    assets:
        - assets/images/

flutter_icons:
    image_path_android: "assets/images/poke.jpg"
    image_path_ios: "assets/images/poke.jpg"
    android: true
    ios: true
    adaptive_icon_foreground: "assets/images/poke_icon.png"
    adaptive_icon_background: "#fff"
